### PR TITLE
Update reqwest to 0.9

### PR DESCRIPTION
**Pull request by jereksel**
Library doesn't build on openssl 1.1.1 (https://github.com/seanmonstar/reqwest/issues/345). New reqwest release should fix that.

### CODE REVIEW

**Comment by jereksel** [comment]
@samrayleung Ready for review

**Comment by samrayleung** [comment]
Before I just thought you are waiting for `reqwest` stable release :) I will review it later, firstly thanks for your contribution .

**Comment by NicoHood** [comment]
Hi,
Could you please tag a new release, so other software that depends on this project can also be updated properly and not rely on a commit hash?

**Comment by samrayleung** [comment]
Of course, I have updated `rspotify` to .0.2.5 :)

**Pull request merged**
